Bump pkl.impl.ghactions to version 1.8.1 (#38)

diff --git a/.github/workflows/prb.yml b/.github/workflows/prb.yml
--- a/.github/workflows/prb.yml
+++ b/.github/workflows/prb.yml
@@ -25,13 +25,17 @@ jobs:
     - name: Build and test
       run: ./gradlew check
   verdict:
-    if: '!cancelled() && !failure()'
+    if: always()
     needs:
     - check-pkl-github-actions
     - build-and-test
     runs-on: ubuntu-latest
     steps:
-    - run: 'true'
+    - name: Failure verdict
+      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+      run: |-
+        echo "Some of the required jobs are either failing or were cancelled"
+        exit 1
   upload-event-file:
     runs-on: ubuntu-latest
     steps:
